---
- name: Download Elastic Agent
  ansible.builtin.get_url:
    url: "{{ elastic_agent_download_base }}/{{ elastic_agent_filename }}"
    dest: "/tmp/{{ elastic_agent_filename }}"
    mode: "0644"
  when: ansible_facts['architecture'] == 'x86_64'
  tags: [monitoring]

- name: Extract Elastic Agent
  ansible.builtin.unarchive:
    src: "/tmp/{{ elastic_agent_filename }}"
    dest: /opt
    remote_src: true
    creates: "/opt/elastic-agent-{{ elastic_agent_version }}-{{ elastic_agent_arch }}"
  when: ansible_facts['architecture'] == 'x86_64'
  tags: [monitoring]

- name: Install Elastic Agent
  ansible.builtin.command:
    cmd: >
      /opt/elastic-agent-{{ elastic_agent_version }}-{{ elastic_agent_arch }}/elastic-agent install
      --non-interactive
      --url="{{ fleet_server_url }}"
      --enrollment-token="{{ fleet_enrollment_token }}"
    creates: /opt/Elastic/Agent/elastic-agent
  when:
    - ansible_facts['architecture'] == 'x86_64'
    - fleet_server_url | length > 0
    - fleet_enrollment_token | length > 0
  tags: [monitoring]

- name: Ensure elastic-agent service is running
  ansible.builtin.service:
    name: elastic-agent
    state: started
    enabled: true
  when:
    - ansible_facts['architecture'] == 'x86_64'
    - fleet_server_url | length > 0
  tags: [monitoring]
