gitlab_external_url: "https://gitlab.lab.local"
nfs_export_path: "/srv/nfs"
restic_repo: "/srv/backup/repo"
restic_password: "{{ vault_restic_password }}"
packages_extra:
  - htop
  - iotop
  - ncdu
  - netcat-openbsd
  - tcpdump
